import React, { useState } from 'react';
import { MeetingAnalysis } from '../types';
import { CheckCircle2, AlertTriangle, HelpCircle, Gavel, FileText, Share2, Copy, FileDown } from 'lucide-react';

interface ClaritySheetProps {
  data: MeetingAnalysis;
  onSeek: (timestamp: string) => void;
}

export const ClaritySheet: React.FC<ClaritySheetProps> = ({ data, onSeek }) => {
  const [activeTab, setActiveTab] = useState<'overview' | 'decisions' | 'actions' | 'risks'>('overview');

  const handleCopy = () => {
    const text = `
Meeting Summary:
${data.summary}

Decisions:
${data.decisions.map(d => `- ${d.decision} (Owner: ${d.owner})`).join('\n')}

Action Items:
${data.actions.map(a => `- [ ] ${a.task} (@${a.owner}, Due: ${a.due})`).join('\n')}

Risks:
${data.risks.map(r => `- ${r.risk} (${r.severity})`).join('\n')}

Open Questions:
${data.openQuestions.map(q => `- ${q.question}`).join('\n')}
    `.trim();
    navigator.clipboard.writeText(text);
    alert('Full summary copied to clipboard!');
  };

  const handleExportPDF = () => {
    window.print();
  };

  const renderTimestamp = (ts: string) => (
    <button 
      onClick={() => onSeek(ts)}
      className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-indigo-50 text-indigo-700 hover:bg-indigo-100 transition-colors print:hidden"
    >
      {ts}
    </button>
  );

  return (
    <div className="clarity-sheet-container bg-white rounded-xl shadow-xl border border-slate-100 overflow-hidden flex flex-col h-full max-h-[85vh]">
      {/* Header */}
      <div className="p-6 border-b border-slate-100 bg-slate-50/50 flex justify-between items-start print:bg-white print:border-none">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">Clarity Sheet</h2>
          <p className="text-sm text-slate-500 mt-1">Generated by Decision Dynamo</p>
          <p className="text-sm text-slate-400 mt-1 hidden print:block">Date: {new Date().toLocaleDateString()}</p>
        </div>
        <div className="flex gap-2 print-hide">
          <button 
            onClick={handleCopy}
            className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-lg hover:bg-slate-50"
          >
            <Copy className="w-4 h-4" /> Copy
          </button>
          <button 
            onClick={handleExportPDF}
            className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700 shadow-sm shadow-indigo-200"
          >
            <FileDown className="w-4 h-4" /> Print / Save as PDF
          </button>
        </div>
      </div>

      {/* Navigation */}
      <div className="flex border-b border-slate-200 px-6 print-hide">
        {[
          { id: 'overview', label: 'Overview', icon: FileText },
          { id: 'decisions', label: 'Decisions', icon: Gavel },
          { id: 'actions', label: 'Action Items', icon: CheckCircle2 },
          { id: 'risks', label: 'Risks & Qs', icon: AlertTriangle },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={`flex items-center gap-2 px-4 py-3 text-sm font-medium border-b-2 transition-colors ${
              activeTab === tab.id 
                ? 'border-indigo-600 text-indigo-600' 
                : 'border-transparent text-slate-500 hover:text-slate-700 hover:border-slate-300'
            }`}
          >
            <tab.icon className="w-4 h-4" />
            {tab.label}
          </button>
        ))}
      </div>

      {/* Content Area */}
      <div className="clarity-content-area flex-1 overflow-y-auto p-6 bg-slate-50/30 print:bg-white print:p-0">
        
        {/* OVERVIEW TAB */}
        <div className={`tab-content ${activeTab === 'overview' ? 'block' : 'hidden'} print:block`}>
          <div className="print-section-header">Overview</div>
          <div className="space-y-6">
            <div className="bg-white p-6 rounded-lg border border-slate-100 shadow-sm print:shadow-none print:border-none print:p-0 print:mb-4">
              <h3 className="text-lg font-semibold text-slate-800 mb-3">Executive Summary</h3>
              <p className="text-slate-600 leading-relaxed whitespace-pre-line">{data.summary}</p>
            </div>
            
            <div className="bg-white p-6 rounded-lg border border-slate-100 shadow-sm print:shadow-none print:border-none print:p-0">
              <h3 className="text-lg font-semibold text-slate-800 mb-3">Key Changes</h3>
              <ul className="space-y-2">
                {data.keyChanges.map((change, i) => (
                  <li key={i} className="flex items-start gap-3">
                    <span className="flex-shrink-0 w-1.5 h-1.5 mt-2 rounded-full bg-indigo-500 print:bg-black" />
                    <span className="text-slate-700">{change}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        {/* DECISIONS TAB */}
        <div className={`tab-content ${activeTab === 'decisions' ? 'block' : 'hidden'} print:block`}>
          <div className="print-section-header">Decisions</div>
          <div className="space-y-4">
            {data.decisions.length === 0 ? (
               <div className="text-center py-10 text-slate-400">No explicit decisions detected.</div>
            ) : (
              data.decisions.map((d, i) => (
                <div key={i} className="bg-white p-4 rounded-lg border border-slate-100 shadow-sm print:shadow-none print:border print:border-slate-300 print:mb-2 page-break-inside-avoid">
                  <div className="flex justify-between items-start mb-2">
                    <div className="text-xs font-bold text-indigo-600 uppercase tracking-wider print:text-black">{d.topic}</div>
                    <span className="print:text-xs print:text-gray-500 print:block hidden">{d.timestamp}</span>
                    {renderTimestamp(d.timestamp)}
                  </div>
                  <h4 className="text-lg font-medium text-slate-900 mb-2">{d.decision}</h4>
                  <div className="flex items-center gap-4 text-sm text-slate-500">
                    <span className="flex items-center gap-1">
                      <span className="font-semibold text-slate-700">Owner:</span> {d.owner}
                    </span>
                    {d.slideRef && (
                      <span className="bg-slate-100 px-2 py-0.5 rounded text-xs border border-slate-200">
                        {d.slideRef}
                      </span>
                    )}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* ACTIONS TAB */}
        <div className={`tab-content ${activeTab === 'actions' ? 'block' : 'hidden'} print:block`}>
          <div className="print-section-header">Action Items</div>
          <div className="bg-white rounded-lg border border-slate-100 shadow-sm print:shadow-none print:border-none">
            <table className="w-full text-left text-sm text-slate-600">
              <thead className="bg-slate-50 border-b border-slate-100 text-slate-800 font-semibold uppercase text-xs tracking-wider print:bg-gray-100">
                <tr>
                  <th className="px-6 py-4">Task</th>
                  <th className="px-6 py-4">Owner</th>
                  <th className="px-6 py-4">Due</th>
                  <th className="px-6 py-4 print:hidden">Timestamp</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {data.actions.map((action, i) => (
                  <tr key={i} className="page-break-inside-avoid">
                    <td className="px-6 py-4 font-medium text-slate-900">{action.task}</td>
                    <td className="px-6 py-4">
                      <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-50 text-blue-700 print:border print:border-gray-300 print:bg-transparent print:text-black">
                        {action.owner}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-slate-500">{action.due || 'ASAP'}</td>
                    <td className="px-6 py-4 print:hidden">{renderTimestamp(action.timestamp)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* RISKS & QUESTIONS TAB */}
        <div className={`tab-content ${activeTab === 'risks' ? 'block' : 'hidden'} print:block`}>
          <div className="print-section-header">Risks & Open Questions</div>
          <div className="space-y-6">
            <div>
              <h3 className="flex items-center gap-2 text-lg font-semibold text-slate-800 mb-4">
                <AlertTriangle className="w-5 h-5 text-amber-500 print:hidden" />
                Detected Risks
              </h3>
              <div className="grid gap-4">
                {data.risks.map((risk, i) => (
                  <div key={i} className="bg-amber-50 border-l-4 border-amber-400 p-4 rounded-r-lg print:bg-white print:border print:border-gray-300 page-break-inside-avoid">
                    <div className="flex justify-between items-start">
                      <h4 className="font-bold text-amber-900 print:text-black">{risk.risk}</h4>
                      <span className="print:text-xs print:text-gray-500 print:block hidden">{risk.timestamp}</span>
                      {renderTimestamp(risk.timestamp)}
                    </div>
                    <p className="text-amber-800 mt-1 text-sm print:text-gray-700">{risk.description}</p>
                    <div className="mt-2 text-xs font-semibold text-amber-700 uppercase tracking-wide print:text-black">
                      Severity: {risk.severity}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="page-break-inside-avoid">
              <h3 className="flex items-center gap-2 text-lg font-semibold text-slate-800 mb-4 print:mt-6">
                <HelpCircle className="w-5 h-5 text-indigo-500 print:hidden" />
                Open Questions
              </h3>
              <div className="bg-white rounded-lg border border-slate-100 shadow-sm p-4 divide-y divide-slate-100 print:border print:border-gray-300">
                {data.openQuestions.map((q, i) => (
                  <div key={i} className="py-3 first:pt-0 last:pb-0 flex justify-between items-center gap-4">
                    <p className="text-slate-700">{q.question}</p>
                    <span className="print:text-xs print:text-gray-500 print:block hidden">{q.timestamp}</span>
                    {renderTimestamp(q.timestamp)}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};